FROM eyeontext/ubuntu_20_04:2.0.2

RUN apt update
RUN apt install -y git
RUN mkdir -p /share/neo4jgithub/eot-wowool-samples
RUN git clone https://github.com/wi18b088/eot-wowool-samples.git /share/neo4jgithub/eot-wowool-samples

# RUN apt install -y vim